apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app-deployment
  namespace: k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
      - name: k8s-app
        image: hadirezaie/k8s-app:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m" # 0.1 cores
            memory: "128Mi"
          limits:
            cpu: "250m" # 0.25 cores
            memory: "256Mi"
