name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
      - name: Build Docker Image
        run: docker build -t your_dockerhub_username/your_app_name:latest .
      - name: Push Docker Image
        run: docker push your_dockerhub_username/your_app_name:latest

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: always
          fields: repo,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}



  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f hpa.yaml

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: always
          fields: repo,commit
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
