name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build project
        run: mvn clean install

      - name: List target directory
        run: ls -la target/  # Verify the JAR file exists

  docker:
    runs-on: ubuntu-latest
    needs: build # Ensure this job runs after the "build" job
    environment: Docker-hub # Reference the environment for Docker secrets
    steps:
      - uses: actions/checkout@v4 # Check out the repository again

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: hadirezaie/kubernetes-springboot
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
